//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decipher.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descriptor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Descriptor()
        {
            this.ReviewResponses = new HashSet<ReviewResponse>();
            this.UserDescriptors = new HashSet<UserDescriptor>();
        }
    
        public int DescriptorID { get; set; }
        public string DescriptorType { get; set; }
        public Nullable<int> AssociatedID { get; set; }
        public string Name { get; set; }
        public int Ordinal { get; set; }
        public Nullable<int> Points { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewResponse> ReviewResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDescriptor> UserDescriptors { get; set; }
    }
}
