//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decipher.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationTarget
    {
        public int NotificationTargetID { get; set; }
        public int NotificationID { get; set; }
        public string TargetType { get; set; }
        public string TargetID { get; set; }
        public string TargetName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Notification Notification { get; set; }
    }
}
