//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decipher.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewResponse
    {
        public int ReviewResponseID { get; set; }
        public int ReviewID { get; set; }
        public int QuestionID { get; set; }
        public int DescriptorID { get; set; }
        public string Detail { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Descriptor Descriptor { get; set; }
        public virtual Question Question { get; set; }
        public virtual Review Review { get; set; }
    }
}
