//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decipher.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDevice
    {
        public int UserDeviceID { get; set; }
        public int UserID { get; set; }
        public string DeviceType { get; set; }
        public string DeviceID { get; set; }
        public string AppVersion { get; set; }
        public string DeviceModel { get; set; }
        public string DevicePlatform { get; set; }
        public string DeviceVersion { get; set; }
        public string DeviceToken { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual AppVersion AppVersion1 { get; set; }
        public virtual User User { get; set; }
    }
}
